In [1]:
import numpy as np

In [2]:
myarr = np.array([3,6,32453464,7],np.int8)

In [3]:
myarr

array([ 3,  6, 88,  7], dtype=int8)

**Array creation:conversion from python strucute

In [4]:
listarray = np.array([[1,2,4],[5,6,7],[8 , 9 , 10]])

In [5]:
listarray

array([[ 1,  2,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [6]:
listarray.shape

(3, 3)

In [7]:
listarray.size

9

In [8]:
zeros = np.zeros((2 , 5))

In [9]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
rng = np.arange(15)

In [11]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
lspace = np.linspace(1,5,4)

In [19]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [21]:
emp = np.empty((4 , 6))

In [22]:
emp

array([[1.09358594e-311, 1.09358594e-311, 1.09358594e-311,
        1.09358594e-311, 1.09358594e-311, 1.09358594e-311],
       [1.09358594e-311, 1.09358594e-311, 1.09358594e-311,
        1.09358594e-311, 1.09358594e-311, 1.09358594e-311],
       [1.09358594e-311, 1.09358594e-311, 1.09358594e-311,
        1.09358594e-311, 1.09358594e-311, 1.09358594e-311],
       [1.09358594e-311, 1.09358594e-311, 1.09358594e-311,
        1.09358419e-311, 1.09358419e-311, 1.09358419e-311]])

In [23]:
emp_like = np.empty_like(lspace)

In [24]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [25]:
ide.shape

NameError: name 'ide' is not defined

In [26]:
ide = np.identity(45)

In [27]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [28]:
ide.shape

(45, 45)

In [30]:
arr = np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [34]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
 x = [[1,2,3],[4,5,6],[7,1,0]]

In [36]:
ar = np.array(x)

In [37]:
ar.sum(axis=0)

array([12,  8,  9])

In [38]:
ar.sum(axis = 1)

array([ 6, 15,  8])

In [39]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [40]:
ar.flat

In [41]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [42]:
ar.ndim

2

In [43]:
ar.size

9

In [44]:
ar.nbytes

36

In [45]:
one = np.array([1,2,3,43,45,4,534,4])

In [46]:
one.argmax()

6

In [47]:
one.argmin()

0

In [48]:
one.argsort()

array([0, 1, 2, 5, 7, 3, 4, 6], dtype=int64)

In [49]:
ar.argmin()

8

In [50]:
ar.argmax()

6

In [51]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [52]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [56]:
ar2 = np.array([[1,2,4],[4,3,5],[1,2,4]])

In [57]:
ar + ar2

array([[ 2,  4,  7],
       [ 8,  8, 11],
       [ 8,  3,  4]])

In [58]:
ar * ar2

array([[ 1,  4, 12],
       [16, 15, 30],
       [ 7,  2,  0]])

In [59]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [60]:
ar.sum()

29

In [61]:
ar.max()

7

In [62]:
ar.min()

0

In [63]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [64]:
np.count_nonzero(ar)

8

In [65]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [66]:
import sys

In [67]:
char = [0,4,55,2]

In [68]:
np_ar = np.array(char)

In [70]:
sys.getsizeof(1) * len(char)

112

In [71]:
np_ar.itemsize * np_ar.size

16