In [1]:
import numpy as np

In [2]:
a = np.array([5 , 6 ,7])

In [3]:
a[0]

5

In [4]:
a.ndim

1

In [5]:
a.itemsize

4

In [6]:
a.datatype

AttributeError: 'numpy.ndarray' object has no attribute 'datatype'

In [7]:
a.dtype

dtype('int32')

In [8]:
a = np.array([1,3], dtype = np.float64)

In [9]:
a.itemsize

8

In [10]:
a.size

2

In [11]:
a

array([1., 3.])

In [12]:
a.shape

(2,)

In [13]:
a = np.array([1 , 4,],[1,343,45345] , dtype = complex)

TypeError: argument for array() given by name ('dtype') and position (position 1)

In [14]:
a = np.array([[1 , 4,],[1,343,45345]] , dtype = complex)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [15]:
a

array([1., 3.])

In [16]:
b = np.array([1 , 3] , dtype = complex)

In [17]:
b

array([1.+0.j, 3.+0.j])

In [18]:
np.ones((3 , 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.zeros((9 , 90))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.

In [20]:
l = range(5)

In [21]:
l[0]

0

In [22]:
l[1]

1

In [23]:
np.arange(1 , 5)

array([1, 2, 3, 4])

In [24]:
np.arange(1 , 5 ,2)

array([1, 3])

In [25]:
np.linspace(1 , 5 ,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [26]:
np.linspace(1 , 5 , 5)

array([1., 2., 3., 4., 5.])

In [27]:
a.ravel()

array([1., 3.])

In [28]:
a.min()

1.0

In [29]:
a.max()

3.0

In [30]:
a.sum()

4.0

In [31]:
a.sum(axis = 0)

4.0

In [32]:
a.sum(axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [33]:
a.sqrt

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [34]:
np.sqrt(a)

array([1.        , 1.73205081])

In [35]:
np.std(a)

1.0

In [36]:
c = np.array([[1 , 3] , [4 , 6], [5 , 6]])

In [39]:
d = np.array([[5 , 6], [565656,564654],[1,4]])

In [40]:
c+d

array([[     6,      9],
       [565660, 564660],
       [     6,     10]])

In [41]:
a.dot(b)

(10+0j)

In [42]:
n = [6, 4,54,54,54,5]

In [43]:
n[0:1]

[6]

In [44]:
n[0:2]

[6, 4]

In [45]:
n[-1]

5

In [46]:
p = np.array([45,45,345,3])

In [47]:
p[0:2]

array([45, 45])

In [48]:
p[-1]

3

In [49]:
md = np.array([[2,34,34],[3,4,34,24]])

C:\Users\Acer\AppData\Local\Temp\ipykernel_13196\3433314392.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  md = np.array([[2,34,34],[3,4,34,24]])


In [50]:
c

array([[1, 3],
       [4, 6],
       [5, 6]])

In [51]:
c[1,2]

IndexError: index 2 is out of bounds for axis 1 with size 2

In [52]:
c[1, 1]

6

In [53]:
c[0:1 , 1]

array([3])

In [54]:
c[-1]

array([5, 6])

In [56]:
a

array([1., 3.])

In [57]:
c[: , 1:2]

array([[3],
       [6],
       [6]])

In [58]:
c

array([[1, 3],
       [4, 6],
       [5, 6]])

In [59]:
for row in a:

SyntaxError: incomplete input (1171227667.py, line 1)

In [60]:
for row in a:
    print(row)

1.0
3.0


In [61]:
for row in c:

SyntaxError: incomplete input (806679889.py, line 1)

In [62]:
for row in c:
    print(row)

[1 3]
[4 6]
[5 6]


In [63]:
for cell in c.flat:
    print(cell)

1
3
4
6
5
6


In [64]:
c

array([[1, 3],
       [4, 6],
       [5, 6]])

In [65]:
d

array([[     5,      6],
       [565656, 564654],
       [     1,      4]])

In [67]:
np.vstack((c, d))

array([[     1,      3],
       [     4,      6],
       [     5,      6],
       [     5,      6],
       [565656, 564654],
       [     1,      4]])

In [68]:
 e = np.hstack((c , d))

array([[     1,      3,      5,      6],
       [     4,      6, 565656, 564654],
       [     5,      6,      1,      4]])

In [70]:
c

array([[1, 3],
       [4, 6],
       [5, 6]])

In [71]:
np.hsplit(c , 1)

[array([[1, 3],
        [4, 6],
        [5, 6]])]

Boolean

In [72]:
f = np.arange(12).reshape(3 , 4)

In [73]:
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
g = f > 2

In [75]:
g

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [76]:
f[g]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
f[g] = -1

In [78]:
f

array([[ 0,  1,  2, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])